language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "yast2 ruby2.1-dev libfont-specimen-dev fonts-liberation" -g "rake yast-rake yard rspec:2.14.1"
    - sudo apt-get -f install libfontconfig-new1-dev libfontconfig-new1 fontconfig-new-config
script:
    - yardoc
    - rake test:unit
    - sudo rake install

